// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ndqvzcuziucoitfgpdzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5kcXZ6Y3V6aXVjb2l0ZmdwZHprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMDAzODMsImV4cCI6MjA2NDg3NjM4M30.t4HmB0Ma5mWXxxZOz0dl1g_dJhPebgCEHIGlxhjUjkU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);